version: "3.7"

services:
  postgres:
    build:
      context: docker
      dockerfile: postgres.dockerfile
    environment:
      POSTGRES_VERSION: ${POSTGRES_VERSION}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - dbpostgres
networks:
  dbpostgres:
    driver: bridge
volumes:
  postgres:
    driver: local